
[General]
	#Let the player pay back his skills
	"Use refund system" = true
	#Initial price refund rate
	#Range: 1 ~ 100
	"refund percentage" = 30
	#Play with badges
	"Use badges" = true
	#Play with mount skills
	"Use mount skills" = true

["XP Requirements"]
	#XP needed to complete level 1
	#Range: 1 ~ 100000
	"Lvl 01 XP" = 100
	#XP needed to complete level 2
	#Range: 1 ~ 100000
	"Lvl 02 XP" = 225
	#XP needed to complete level 3
	#Range: 1 ~ 100000
	"Lvl 03 XP" = 350
	#XP needed to complete level 4
	#Range: 1 ~ 100000
	"Lvl 04 XP" = 475
	#XP needed to complete level 5
	#Range: 1 ~ 100000
	"Lvl 05 XP" = 600
	#XP needed to complete level 6
	#Range: 1 ~ 100000
	"Lvl 06 XP" = 725
	#XP needed to complete level 7
	#Range: 1 ~ 100000
	"Lvl 07 XP" = 850
	#XP needed to complete level 8
	#Range: 1 ~ 100000
	"Lvl 08 XP" = 975
	#XP needed to complete level 9
	#Range: 1 ~ 100000
	"Lvl 09 XP" = 1100
	#XP needed to complete level 10
	#Range: 1 ~ 100000
	"Lvl 10 XP" = 1225
	#XP needed to complete level 11
	#Range: 1 ~ 100000
	"Lvl 11 XP" = 1475
	#XP needed to complete level 12
	#Range: 1 ~ 100000
	"Lvl 12 XP" = 1725
	#XP needed to complete level 13
	#Range: 1 ~ 100000
	"Lvl 13 XP" = 1975
	#XP needed to complete level 14
	#Range: 1 ~ 100000
	"Lvl 14 XP" = 2225
	#XP needed to complete level 15
	#Range: 1 ~ 100000
	"Lvl 15 XP" = 2475
	#XP needed to complete level 16
	#Range: 1 ~ 100000
	"Lvl 16 XP" = 2725
	#XP needed to complete level 17
	#Range: 1 ~ 100000
	"Lvl 17 XP" = 2975
	#XP needed to complete level 18
	#Range: 1 ~ 100000
	"Lvl 18 XP" = 3225
	#XP needed to complete level 19
	#Range: 1 ~ 100000
	"Lvl 19 XP" = 3475
	#XP needed to complete level 20
	#Range: 1 ~ 100000
	"Lvl 20 XP" = 3750
	#XP needed to complete level 21
	#Range: 1 ~ 100000
	"Lvl 21 XP" = 4275
	#XP needed to complete level 22
	#Range: 1 ~ 100000
	"Lvl 22 XP" = 4800
	#XP needed to complete level 23
	#Range: 1 ~ 100000
	"Lvl 23 XP" = 5325
	#XP needed to complete level 24
	#Range: 1 ~ 100000
	"Lvl 24 XP" = 5850
	#XP needed to complete level 25
	#Range: 1 ~ 100000
	"Lvl 25 XP" = 6375
	#XP needed to complete level 26
	#Range: 1 ~ 100000
	"Lvl 26 XP" = 6900
	#XP needed to complete level 27
	#Range: 1 ~ 100000
	"Lvl 27 XP" = 7425
	#XP needed to complete level 28
	#Range: 1 ~ 100000
	"Lvl 28 XP" = 7950
	#XP needed to complete level 29
	#Range: 1 ~ 100000
	"Lvl 29 XP" = 8475
	#XP needed to complete level 30
	#Range: 1 ~ 100000
	"Lvl 30 XP" = 9000
	#XP needed to complete level 31
	#Range: 1 ~ 100000
	"Lvl 31 XP" = 9600
	#XP needed to complete level 32
	#Range: 1 ~ 100000
	"Lvl 32 XP" = 10200
	#XP needed to complete level 33
	#Range: 1 ~ 100000
	"Lvl 33 XP" = 10800
	#XP needed to complete level 34
	#Range: 1 ~ 100000
	"Lvl 34 XP" = 11400
	#XP needed to complete level35
	#Range: 1 ~ 100000
	"Lvl 35 XP" = 12000
	#XP needed to complete level 36
	#Range: 1 ~ 100000
	"Lvl 36 XP" = 12600
	#XP needed to complete level 37
	#Range: 1 ~ 100000
	"Lvl 37 XP" = 13200
	#XP needed to complete level 38
	#Range: 1 ~ 100000
	"Lvl 38 XP" = 13800
	#XP needed to complete level 39
	#Range: 1 ~ 100000
	"Lvl 39 XP" = 14400
	#XP needed to complete 40+ levels
	#Range: 1 ~ 100000
	"Lvl max XP" = 15000

[Skills]
	#Prices for health skill
	"Health skill prices" = [2, 2, 3, 3, 5, 5, 7, 7, 9, 9]
	#Prices for reach skill
	"Reach skill prices" = [3, 5, 9, 13]
	#Prices for resistance skill
	"Resistance skill prices" = [3, 5, 7, 9, 13]
	#Prices for attack damage skill
	"Attack damage skill prices" = [9, 14]
	#Prices for speed skill
	"Speed skill prices" = [2, 4, 6, 8, 11]
	#Prices for step height skill
	"Step height skill prices" = [3, 5]
	#Prices for swim speed skill
	"Swim speed skill prices" = [2, 4, 6, 8, 11]
	#Prices for bloodlust skill
	"Bloodlust skill prices" = [4, 7]
	#Prices for damage deal skill
	"Damage deal skill prices" = [3, 5, 7, 9, 13]
	#Prices for critical hit skill
	"Critical hit skill prices" = [4, 7, 9, 10, 15]
	#Prices for venomous attack skill
	"Venomous attack skill prices" = [3, 5, 7, 9, 13]
	#Prices for skill xp boost skill
	"Skill xp boost prices" = [5, 8, 12, 16]
	#Prices for harvester skill
	"Harvester skill prices" = [9, 14]
	#Prices for nutrtition boost skill
	"Nutrition boost skill prices" = [2, 4, 6, 8, 11]
	#Prices for xp boost skill
	"Xp boost skill prices" = [3, 5, 7, 9]
	#Prices for magnet skill
	"Magnet skill prices" = [3, 5, 7, 9, 13]
	#Price for second life skill
	"Price for second life skill" = [20]
	#Price for edible rotten flesh skill
	"Edible rotten flesh skill prices" = [12]
	#Price for villager bait skill
	"Villager bait skill prices" = [12]
	#Price for Night vision skill
	"Night vision skill prices" = [18]
	#Price for fire resistance skill
	"Fire resistance skill prices" = [18]
	#Price for friendly piglins skill
	"Friendly piglins skill prices" = [12]

["Mount skills"]
	#Prices for max health mount skill
	"Max health mount skill prices" = [3, 5, 7, 9]
	#Prices for speed mount skill
	"Speed mount skill prices" = [12]
	#Prices for jump height mount skill
	"Jump height mount skill prices" = [12]
	#Prices for resistance mount skill
	"Resistance mount skill prices" = [12]

[Badges]
	#=== BE CAREFUL WHEN MODIFYING THESE VALUES TO MAINTAIN CONSISTENCY WITH XP GAINS ===
	#Nature destroyer xp goals
	"Nature destroyer xp goals" = [2500, 10000, 18000, 35000]
	#Meat collector xp goals
	"Meat collector xp goals" = [850, 3500, 9000, 17000]
	#Certified Gobbler xp goals
	"Certified Gobbler xp goals" = [200, 850, 1750, 4500]
	#Tinkerer's way xp goals
	"Tinkerer' way xp goals" = [1500, 4000, 8500, 17500]

["XP earnings"]
	#=== BE CAREFUL WHEN MODIFYING THESE VALUES TO MAINTAIN CONSISTENCY WITH THE BADGE GOALS ===
	#XP gains when you eat food
	#Range: 0.0 ~ 100000.0
	"Eating gains" = 1.0
	#XP gains when you craft an item
	#Range: 0.0 ~ 100000.0
	"Crafting gains" = 0.5
	#XP gains when you fish
	#Range: 0.0 ~ 100000.0
	"Fushing gains" = 5.0
	#XP gains when you turn dirt into farmlands
	#Range: 0.0 ~ 100000.0
	"Harvesting gains" = 2.0
	#XP gains when you block damage with a shield
	#Range: 0.0 ~ 100000.0
	"Blocking damamges gains" = 2.0
	#XP gains after sleeping
	#Range: 0.0 ~ 100000.0
	"Sleeping gains" = 5.0

